# -*- coding: utf-8 -*-
"""Lat/Lon_to_cartesian_cam.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ndB9tswaLaJMeQo2xf-MJshh4ZB-fkl-
"""

import numpy as np

#enter location and ht from earth(in m)
lat=90 
lon=0
ht_from_earth=500

#(lat, lon) notation
#function takes x axis along (0,0), y axis along (0,90) and z axis through the poles
def get_cartesian(lat, lon, ht_from_earth):
  lat, lon= np.deg2rad(lat), np.deg2rad(lon)
  R=6371500
  x=(R+ht_from_earth)*np.cos(lat)*np.cos(lon)
  y=(R+ht_from_earth)*np.cos(lat)*np.sin(lon)
  z=(R+ht_from_earth)*np.sin(lat)
  return x,y,z

get_cartesian(lat, lon, ht_from_earth)

